import MarkdownIt from 'markdown-it';

// Renders an article body (markdown) to HTML for the news template.
//
// SECURITY: article bodies are LLM-generated by the whitespace-agent from
// untrusted news sources, then injected via `set:html`. markdown-it runs with
// `html: false` (its default, set explicitly here), so any raw HTML in the
// source — including <script> — is escaped to text and never rendered as live
// markup. Default link validation also rejects `javascript:` URLs. This is why
// we use markdown-it rather than Astro's createMarkdownProcessor, which hardcodes
// rehype-raw + allowDangerousHtml and would pass raw HTML straight through.
const md = new MarkdownIt({
  html: false, // do NOT interpret raw HTML in source — escape it (XSS guard)
  linkify: true, // turn bare URLs into links
  typographer: false,
});

export function renderArticleBody(src: string): string {
  return md.render(src);
}
